### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by Dandigit** [enact-lang/enact#35]
Ask away!

**Comment by BonfireScratch** [comment]
Well, we would like you to fix the bug about the dictionary, could you do that please?

**Comment by BonfireScratch** [comment]
@Dandigit what can Enact do?

**Comment by Dandigit** [comment]
@BonfireScratch Right now, Enact's implementation is just a parser. (I'm working on an analyser right now.) It can parse the full syntax of Enact, like if statements, loops, iterators, traits, structs, expressions, etc.

It's a big project and there's going to be a lot of code that has to be written before Enact is fully functional.

**Comment by BonfireScratch** [comment]
@Dandigit will Enact have a website?

**Comment by Dandigit** [comment]
@BonfireScratch Eventually, I imagine - but I'd rather focus on the important things, for now.

**Comment by BonfireScratch** [comment]
@Dandigit I guess I could do one for you

**Comment by Dandigit** [comment]
@BonfireScratch Thanks for the offer, but no, it's really not necessary at this stage.

**Comment by SimpleBinary** [comment]
@Dandigit What would a variable declaration look like? I just don't want this to be like python where you have to put `global x` because it doesn't know whether you are creating or editing a variable.

**Comment by Dandigit** [comment]
@SimpleBinary All variable declarations are the same, whether at a global or local level.
```
// Mutable
var foo = 2
foo = 4

// Constant
const boo = 2
boo = 4 // Compile error!
```

**Comment by BonfireScratch** [comment]
@Dandigit will the language feature garbage collection?

**Comment by Dandigit** [comment]
@BonfireScratch Yes, Enact will feature a garbage collector. Users who need extra performabce will also be able to turn it off and manage memory themselves, if they so please, or write their own memory managers.

**Comment by BonfireScratch** [comment]
@Dandigit does Enact use mutable or immutable classes?

**Comment by Dandigit** [comment]
@BonfireScratch Enact uses both, depending on how you instantiate the class, e.g:
```
// Given this struct
struct Person:
    name String
    age int

    // Mutating method
    fun rename(name String):
        .name = name
    end

    // Non-mutating method
    fun printName():
        print(.name)
    end
end

/* Mutable */
var jim = Person("Jim", 42)

// So we can set fields
jim.age = 99

// And call mutating methods
jim.rename("John")

// And call non-mutating methods
jim.printName()


/* Immutable */
const sam = Person("Sam", 88)

// So we cannot set fields
sam.age = 21 // Compile error!

// And we cannot call mutating methods
sam.rename("Sally") // Compile error!

// We can still call non-mutating methods
sam.printName() // This is fine!
```

**Comment by BonfireScratch** [comment]
@Dandigit I wasn't clear enough... I mean in the implementation.

**Comment by Dandigit** [comment]
@BonfireScratch Well it depends on the part of the implementation you're looking at? C++ offers both for different use cases.

- The AST (`Expr`/`Stmt`) classes are used as mutable, although they really shouldn't be - I am working on changing the way analysis works in the future to remedy this
- The type graph (subclasses of `TypeBase`) which the analyser builds up is basically immutable
- Bytecode (the `Chunk` class) is treated as mutable by the compiler, but immutable by the VM
- The class `Value` and subclasses of `Object` are usually treated as immutable, but not marked as such, because the exception of `var`-instantiated arrays and classes shown above applies

**Comment by BonfireScratch** [comment]
@Dandigit how do you plan to implement interop with other languages?

**Comment by Dandigit** [comment]
@BonfireScratch First I'll implement a C FFI, which will load compiled DLLs/shared objects with `dlopen`/`LoadLibrary` and look up symbols within them with `dlsym`/`GetProcAddress`. 

To locate symbols with the correct type information, the user will have to declare them somehow. I plan to allow the user to pass in a C header file to be parsed at compile time. Alternatively they can declare each symbol themselves.

This would look something like:
```
import std.cffi.CLibrary

// Load the binary
let library = CLibrary.load("./library.dll")

// Declare symbols by including a header
library.#include("./library.h")

// Alternatively, we could declare them ourselves
// library.declare("myAddFunc", fun (int, int) int)

// Look up symbols and use them
library["myAddFunc"](2, 45)
// => 47
```

That `#` syntax isn't final, but it indicates compile time execution of code. This is handy because it means that we don't have to parse the C header more than once.

From here, I can use this C FFI to write an Enact library that interfaces with CPython and allows the user to interact with Python modules. In the same way, I can use Python's C FFI to write a library that interfaces with the Enact implementation and allows the user to interact with Enact modules. Python is particularly convenient in this regard, allowing you to define custom import semantics. This could allow something like:
```
import enact

// We can directly import an Enact file or module called enact_module now!
import enact_module

enact_module.doSomething(3, 4)
```

C++ interop is a great deal harder due to the lack of a stable ABI and general language complexity. I will likely require that the user exposes their C++ code to the C FFI by using `extern "C"`. This isn't the cleanest possible solution, but it would work with relative stability.
